/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day1

import util.FileUtil
import kotlin.test.Test
import kotlin.test.assertEquals

class DayOneTest {
    @Test fun testPartOne() {
        val classUnderTest = DayOne()

        val data = FileUtil().readResource("/input") ?: return
        val input = data.lines().filter { it != "" }.map { it.toInt() }

        assertEquals(902451, classUnderTest.partOne(input))
    }

    @Test fun testPartTwo() {
        val classUnderTest = DayOne()

        val data = FileUtil().readResource("/input") ?: return
        val input = data.lines().filter { it != "" }.map { it.toInt() }

        assertEquals(85555470, classUnderTest.partTwo(input))
    }
}
