name: 2021 tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "2021/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "2021/**"
  workflow_dispatch:
    branches: [ "main" ]

defaults:
  run:
    working-directory: "2021"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm ci
      - run: npm test
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 2021 test results
          path: 2021/build/test-results/**/*.xml
          reporter: jest-junit
