name: 2025 tests

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/2025.yml"
      - ".github/workflows/go.yml"
      - "go/framework/**"
      - "go/2025/**"
  pull_request:
    paths:
      - ".github/workflows/2025.yml"
      - ".github/workflows/go.yml"
      - "go/framework/**"
      - "go/2025/**"
  workflow_dispatch:

jobs:
  run-workflow:
    uses: ./.github/workflows/go.yml
    with:
      year: 2025